name: Python Package Publisher

# This workflow handles building and publishing the Python package to PyPI.
# Testing and linting are handled by the ci.yml workflow.

on:
  release:
    types: [published] # Trigger when a release is published

jobs:
  build-and-publish:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      shell: bash

    - name: Check uv version
      run: uv --version

    # No caching needed here as we only install build tools, not project deps

    - name: Install build dependencies
      run: uv pip install --system build twine # Install build tools globally in the runner env

    - name: Build package
      run: python -m build

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      # No 'with' section needed for trusted publishing; it uses OIDC token by default